### ISSUE TITLE
Faulty game end condition

### ISSUE THREAD

**Issue by Sheeo** [FAForever/faf-phantomx#9]
[Original bug report](http://forums.faforever.com/forums/viewtopic.php?f=3&p=101452#p101452)

**Comment by j-brewer** [comment]
This bug is a result of old code in the aibrain.lua file that the Phantom-X mod uses.  I've updated the Phantom-X code to match the current FAF code.

**Comment by Sheeo** [comment]
Done in https://github.com/FAForever/faf-phantomx/commit/54f6f51a570023fc96bbbc7b4667641b83e60334

I suggest making a diff between the `aibrain.lua` file used by phantom-x and that used by current FAF, and then using a hook file instead -- while that may break with updates it should be less likely.

Good work fixing this :)
